repos:
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.13
    hooks:
        - id: insert-license
          files: composer
          args:
            - --license-filepath
            - LICENSE_HEADER
            - --comment-style
            - "#"

