train_dataset:
  c4:
    split: train
    max_samples: 10240000 # 1e10 tok ~= 10240000[sa] * 1024[msl] = 20000[ba] * 512[bs] * 1024[msl]
    max_seq_len: 1024
    tokenizer_name: gpt2
    group_method: concat
    seed: 17
    shuffle: true
    drop_last: true
val_dataset:
  c4:
    split: validation
    max_samples: 102400 # Approx 100k samples
    max_seq_len: 1024
    tokenizer_name: gpt2
    group_method: truncate
    seed: 17
    shuffle: false
    drop_last: false
model:
  gpt2:
    use_pretrained: false
    tokenizer_name: gpt2
    gradient_checkpointing: false
    model_config:
      n_embd: 1280
      n_head: 20
      n_layer: 36
      n_positions: 1024
optimizer:
  decoupled_adamw:
    lr: 6.0e-4
    betas:
      - 0.9
      - 0.95
    eps: 1.0e-08
    weight_decay: 0.0
schedulers:
  - constant_with_warmup:
      t_warmup: 0.01dur
loggers:
  - tqdm: {}
max_duration: 1ep
train_batch_size: 512
eval_batch_size: 64
seed: 17
device:
  gpu: {}
dataloader:
  pin_memory: true
  persistent_workers: true
  num_workers: 8
  timeout: 0
  prefetch_factor: 2
precision: amp
grad_clip_norm: 1.0
grad_accum: 8 # 512[bs] // 8 [devices] // 8 [max_microbatch_per_device] = 8 [ga], assuming 8xA100-40GB
validate_every_n_batches: 1000
validate_every_n_epochs: 1
